### ISSUE TITLE
'bot is not defined' error.

### ISSUE THREAD

**Issue by TechDufus** [xdega/NerdBot#15]
@bot.command line in each bot_command .py file errors:

```
2021-01-30T06:13:41.000000+00:00 app[api]: Build started by user xdega121@gmail.com
2021-01-30T06:14:04.268446+00:00 app[api]: Release v17 created by user xdega121@gmail.com
2021-01-30T06:14:05.097738+00:00 heroku[worker.1]: State changed from crashed to starting
2021-01-30T06:14:04.268446+00:00 app[api]: Deploy 83c07433 by user xdega121@gmail.com
2021-01-30T06:14:09.623696+00:00 heroku[worker.1]: Starting process with command `python bot.py`
2021-01-30T06:14:10.325257+00:00 heroku[worker.1]: State changed from starting to up
2021-01-30T06:14:14.000000+00:00 app[api]: Build succeeded
2021-01-30T06:14:14.920087+00:00 heroku[worker.1]: Process exited with status 1
2021-01-30T06:14:14.971470+00:00 heroku[worker.1]: State changed from up to crashed
2021-01-30T06:14:14.796793+00:00 app[worker.1]: Traceback (most recent call last):
2021-01-30T06:14:14.796853+00:00 app[worker.1]:   File "/app/bot.py", line 34, in <module>
2021-01-30T06:14:14.797013+00:00 app[worker.1]:     import bot_commands
2021-01-30T06:14:14.797014+00:00 app[worker.1]:   File "/app/bot_commands/__init__.py", line 3, in <module>
2021-01-30T06:14:14.797157+00:00 app[worker.1]:     from . import help
2021-01-30T06:14:14.797193+00:00 app[worker.1]:   File "/app/bot_commands/help.py", line 1, in <module>
2021-01-30T06:14:14.797321+00:00 app[worker.1]:     @bot.command(pass_context=True)
2021-01-30T06:14:14.797401+00:00 app[worker.1]: NameError: name 'bot' is not defined
```

Need to investigate possible scoping issues with @bot.command from 'nested' .py files not referencing the bot definition inside bot.py line 17.

**Comment by xdega** [comment]
@matthewjdegarmo 

I browsed some other Python discord bots here on GH, and found the following repo that is relatively small and illustrates a common structure for organizing discord bot code: https://github.com/AlexFlipnote/discord_bot.py

I think we should go through that code, and use it as inspiration for refactoring our command code. This would also mean cutting out the "middle man", and simply just making the jump to an OOP approach, or at least a structure that uses classes to organize our bot commands.
 
Of particular note, I am seeing use of a structure called "cogs", which is documented here: 
https://discordpy.readthedocs.io/en/latest/ext/commands/cogs.html

**Comment by xdega** [comment]
@matthewjdegarmo I am going to take responsibility for a complete restructure of the bot setup here. It is my mess, and I think it makes more sense due to my easier access to deployment\build logs (there may be quite a bit of trial and error here).

Of course, I think that having a better way to work with bot commands locally will be ideal in the future. But lets just get this thing working for now.
